name: push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: make ci

      - name: Build image
        run: docker compose -f docker-compose.yml build app
